version: '3.4'

services:
  db:
    image: mysql:5.7.22
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile    
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_udemy
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  restwithaspnetudemy:
    image: restwithaspnetudemy-api
    build:
      context: .
      dockerfile: RestWithASPNETUdemy/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    links:
      -db
    depends_on:
      -db
    ports:
      - "5000:80"
    networks:
      - udemy-network
    
networks:
    udemy-network:
    driver: bridge
